/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as RealEstateRouteImport } from './routes/real-estate'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as TestimonialsRouteImport } from './routes/testimonials'
import { Route as EcosystemsIndexRouteImport } from './routes/ecosystems.index'
import { Route as EcosystemsSlugRouteImport } from './routes/ecosystems.$slug'
import { Route as InsightsSlugRouteImport } from './routes/insights.$slug'
import { Route as RealEstatePlotsRouteImport } from './routes/real-estate.plots'
import { Route as RealEstateProjectsRouteImport } from './routes/real-estate.projects'
import { Route as RealEstatePropertiesRouteImport } from './routes/real-estate.properties'
import { Route as ServicesSlugRouteImport } from './routes/services.$slug'
import { Route as RealEstatePlotsSlugRouteImport } from './routes/real-estate.plots.$slug'
import { Route as RealEstateProjectsSlugRouteImport } from './routes/real-estate.projects.$slug'
import { Route as RealEstatePropertiesSlugRouteImport } from './routes/real-estate.properties.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const RealEstateRoute = RealEstateRouteImport.update({
  id: '/real-estate',
  path: '/real-estate',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const TestimonialsRoute = TestimonialsRouteImport.update({
  id: '/testimonials',
  path: '/testimonials',
  getParentRoute: () => rootRouteImport,
} as any)
const EcosystemsIndexRoute = EcosystemsIndexRouteImport.update({
  id: '/ecosystems/',
  path: '/ecosystems/',
  getParentRoute: () => rootRouteImport,
} as any)
const EcosystemsSlugRoute = EcosystemsSlugRouteImport.update({
  id: '/ecosystems/$slug',
  path: '/ecosystems/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsSlugRoute = InsightsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => InsightsRoute,
} as any)
const RealEstatePlotsRoute = RealEstatePlotsRouteImport.update({
  id: '/plots',
  path: '/plots',
  getParentRoute: () => RealEstateRoute,
} as any)
const RealEstateProjectsRoute = RealEstateProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => RealEstateRoute,
} as any)
const RealEstatePropertiesRoute = RealEstatePropertiesRouteImport.update({
  id: '/properties',
  path: '/properties',
  getParentRoute: () => RealEstateRoute,
} as any)
const ServicesSlugRoute = ServicesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ServicesRoute,
} as any)
const RealEstatePlotsSlugRoute = RealEstatePlotsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => RealEstatePlotsRoute,
} as any)
const RealEstateProjectsSlugRoute = RealEstateProjectsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => RealEstateProjectsRoute,
} as any)
const RealEstatePropertiesSlugRoute =
  RealEstatePropertiesSlugRouteImport.update({
    id: '/$slug',
    path: '/$slug',
    getParentRoute: () => RealEstatePropertiesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/insights': typeof InsightsRouteWithChildren
  '/portfolio': typeof PortfolioRoute
  '/real-estate': typeof RealEstateRouteWithChildren
  '/services': typeof ServicesRouteWithChildren
  '/testimonials': typeof TestimonialsRoute
  '/ecosystems/$slug': typeof EcosystemsSlugRoute
  '/insights/$slug': typeof InsightsSlugRoute
  '/real-estate/plots': typeof RealEstatePlotsRouteWithChildren
  '/real-estate/projects': typeof RealEstateProjectsRouteWithChildren
  '/real-estate/properties': typeof RealEstatePropertiesRouteWithChildren
  '/services/$slug': typeof ServicesSlugRoute
  '/ecosystems/': typeof EcosystemsIndexRoute
  '/real-estate/plots/$slug': typeof RealEstatePlotsSlugRoute
  '/real-estate/projects/$slug': typeof RealEstateProjectsSlugRoute
  '/real-estate/properties/$slug': typeof RealEstatePropertiesSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/insights': typeof InsightsRouteWithChildren
  '/portfolio': typeof PortfolioRoute
  '/real-estate': typeof RealEstateRouteWithChildren
  '/services': typeof ServicesRouteWithChildren
  '/testimonials': typeof TestimonialsRoute
  '/ecosystems/$slug': typeof EcosystemsSlugRoute
  '/insights/$slug': typeof InsightsSlugRoute
  '/real-estate/plots': typeof RealEstatePlotsRouteWithChildren
  '/real-estate/projects': typeof RealEstateProjectsRouteWithChildren
  '/real-estate/properties': typeof RealEstatePropertiesRouteWithChildren
  '/services/$slug': typeof ServicesSlugRoute
  '/ecosystems': typeof EcosystemsIndexRoute
  '/real-estate/plots/$slug': typeof RealEstatePlotsSlugRoute
  '/real-estate/projects/$slug': typeof RealEstateProjectsSlugRoute
  '/real-estate/properties/$slug': typeof RealEstatePropertiesSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/insights': typeof InsightsRouteWithChildren
  '/portfolio': typeof PortfolioRoute
  '/real-estate': typeof RealEstateRouteWithChildren
  '/services': typeof ServicesRouteWithChildren
  '/testimonials': typeof TestimonialsRoute
  '/ecosystems/$slug': typeof EcosystemsSlugRoute
  '/insights/$slug': typeof InsightsSlugRoute
  '/real-estate/plots': typeof RealEstatePlotsRouteWithChildren
  '/real-estate/projects': typeof RealEstateProjectsRouteWithChildren
  '/real-estate/properties': typeof RealEstatePropertiesRouteWithChildren
  '/services/$slug': typeof ServicesSlugRoute
  '/ecosystems/': typeof EcosystemsIndexRoute
  '/real-estate/plots/$slug': typeof RealEstatePlotsSlugRoute
  '/real-estate/projects/$slug': typeof RealEstateProjectsSlugRoute
  '/real-estate/properties/$slug': typeof RealEstatePropertiesSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/careers'
    | '/contact'
    | '/insights'
    | '/portfolio'
    | '/real-estate'
    | '/services'
    | '/testimonials'
    | '/ecosystems/$slug'
    | '/insights/$slug'
    | '/real-estate/plots'
    | '/real-estate/projects'
    | '/real-estate/properties'
    | '/services/$slug'
    | '/ecosystems/'
    | '/real-estate/plots/$slug'
    | '/real-estate/projects/$slug'
    | '/real-estate/properties/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/careers'
    | '/contact'
    | '/insights'
    | '/portfolio'
    | '/real-estate'
    | '/services'
    | '/testimonials'
    | '/ecosystems/$slug'
    | '/insights/$slug'
    | '/real-estate/plots'
    | '/real-estate/projects'
    | '/real-estate/properties'
    | '/services/$slug'
    | '/ecosystems'
    | '/real-estate/plots/$slug'
    | '/real-estate/projects/$slug'
    | '/real-estate/properties/$slug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/careers'
    | '/contact'
    | '/insights'
    | '/portfolio'
    | '/real-estate'
    | '/services'
    | '/testimonials'
    | '/ecosystems/$slug'
    | '/insights/$slug'
    | '/real-estate/plots'
    | '/real-estate/projects'
    | '/real-estate/properties'
    | '/services/$slug'
    | '/ecosystems/'
    | '/real-estate/plots/$slug'
    | '/real-estate/projects/$slug'
    | '/real-estate/properties/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CareersRoute: typeof CareersRoute
  ContactRoute: typeof ContactRoute
  InsightsRoute: typeof InsightsRouteWithChildren
  PortfolioRoute: typeof PortfolioRoute
  RealEstateRoute: typeof RealEstateRouteWithChildren
  ServicesRoute: typeof ServicesRouteWithChildren
  TestimonialsRoute: typeof TestimonialsRoute
  EcosystemsSlugRoute: typeof EcosystemsSlugRoute
  EcosystemsIndexRoute: typeof EcosystemsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/real-estate': {
      id: '/real-estate'
      path: '/real-estate'
      fullPath: '/real-estate'
      preLoaderRoute: typeof RealEstateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/testimonials': {
      id: '/testimonials'
      path: '/testimonials'
      fullPath: '/testimonials'
      preLoaderRoute: typeof TestimonialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ecosystems/': {
      id: '/ecosystems/'
      path: '/ecosystems'
      fullPath: '/ecosystems/'
      preLoaderRoute: typeof EcosystemsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ecosystems/$slug': {
      id: '/ecosystems/$slug'
      path: '/ecosystems/$slug'
      fullPath: '/ecosystems/$slug'
      preLoaderRoute: typeof EcosystemsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights/$slug': {
      id: '/insights/$slug'
      path: '/$slug'
      fullPath: '/insights/$slug'
      preLoaderRoute: typeof InsightsSlugRouteImport
      parentRoute: typeof InsightsRoute
    }
    '/real-estate/plots': {
      id: '/real-estate/plots'
      path: '/plots'
      fullPath: '/real-estate/plots'
      preLoaderRoute: typeof RealEstatePlotsRouteImport
      parentRoute: typeof RealEstateRoute
    }
    '/real-estate/projects': {
      id: '/real-estate/projects'
      path: '/projects'
      fullPath: '/real-estate/projects'
      preLoaderRoute: typeof RealEstateProjectsRouteImport
      parentRoute: typeof RealEstateRoute
    }
    '/real-estate/properties': {
      id: '/real-estate/properties'
      path: '/properties'
      fullPath: '/real-estate/properties'
      preLoaderRoute: typeof RealEstatePropertiesRouteImport
      parentRoute: typeof RealEstateRoute
    }
    '/services/$slug': {
      id: '/services/$slug'
      path: '/$slug'
      fullPath: '/services/$slug'
      preLoaderRoute: typeof ServicesSlugRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/real-estate/plots/$slug': {
      id: '/real-estate/plots/$slug'
      path: '/$slug'
      fullPath: '/real-estate/plots/$slug'
      preLoaderRoute: typeof RealEstatePlotsSlugRouteImport
      parentRoute: typeof RealEstatePlotsRoute
    }
    '/real-estate/projects/$slug': {
      id: '/real-estate/projects/$slug'
      path: '/$slug'
      fullPath: '/real-estate/projects/$slug'
      preLoaderRoute: typeof RealEstateProjectsSlugRouteImport
      parentRoute: typeof RealEstateProjectsRoute
    }
    '/real-estate/properties/$slug': {
      id: '/real-estate/properties/$slug'
      path: '/$slug'
      fullPath: '/real-estate/properties/$slug'
      preLoaderRoute: typeof RealEstatePropertiesSlugRouteImport
      parentRoute: typeof RealEstatePropertiesRoute
    }
  }
}

interface InsightsRouteChildren {
  InsightsSlugRoute: typeof InsightsSlugRoute
}

const InsightsRouteChildren: InsightsRouteChildren = {
  InsightsSlugRoute: InsightsSlugRoute,
}

const InsightsRouteWithChildren = InsightsRoute._addFileChildren(
  InsightsRouteChildren,
)

interface RealEstatePlotsRouteChildren {
  RealEstatePlotsSlugRoute: typeof RealEstatePlotsSlugRoute
}

const RealEstatePlotsRouteChildren: RealEstatePlotsRouteChildren = {
  RealEstatePlotsSlugRoute: RealEstatePlotsSlugRoute,
}

const RealEstatePlotsRouteWithChildren = RealEstatePlotsRoute._addFileChildren(
  RealEstatePlotsRouteChildren,
)

interface RealEstateProjectsRouteChildren {
  RealEstateProjectsSlugRoute: typeof RealEstateProjectsSlugRoute
}

const RealEstateProjectsRouteChildren: RealEstateProjectsRouteChildren = {
  RealEstateProjectsSlugRoute: RealEstateProjectsSlugRoute,
}

const RealEstateProjectsRouteWithChildren =
  RealEstateProjectsRoute._addFileChildren(RealEstateProjectsRouteChildren)

interface RealEstatePropertiesRouteChildren {
  RealEstatePropertiesSlugRoute: typeof RealEstatePropertiesSlugRoute
}

const RealEstatePropertiesRouteChildren: RealEstatePropertiesRouteChildren = {
  RealEstatePropertiesSlugRoute: RealEstatePropertiesSlugRoute,
}

const RealEstatePropertiesRouteWithChildren =
  RealEstatePropertiesRoute._addFileChildren(RealEstatePropertiesRouteChildren)

interface RealEstateRouteChildren {
  RealEstatePlotsRoute: typeof RealEstatePlotsRouteWithChildren
  RealEstateProjectsRoute: typeof RealEstateProjectsRouteWithChildren
  RealEstatePropertiesRoute: typeof RealEstatePropertiesRouteWithChildren
}

const RealEstateRouteChildren: RealEstateRouteChildren = {
  RealEstatePlotsRoute: RealEstatePlotsRouteWithChildren,
  RealEstateProjectsRoute: RealEstateProjectsRouteWithChildren,
  RealEstatePropertiesRoute: RealEstatePropertiesRouteWithChildren,
}

const RealEstateRouteWithChildren = RealEstateRoute._addFileChildren(
  RealEstateRouteChildren,
)

interface ServicesRouteChildren {
  ServicesSlugRoute: typeof ServicesSlugRoute
}

const ServicesRouteChildren: ServicesRouteChildren = {
  ServicesSlugRoute: ServicesSlugRoute,
}

const ServicesRouteWithChildren = ServicesRoute._addFileChildren(
  ServicesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CareersRoute: CareersRoute,
  ContactRoute: ContactRoute,
  InsightsRoute: InsightsRouteWithChildren,
  PortfolioRoute: PortfolioRoute,
  RealEstateRoute: RealEstateRouteWithChildren,
  ServicesRoute: ServicesRouteWithChildren,
  TestimonialsRoute: TestimonialsRoute,
  EcosystemsSlugRoute: EcosystemsSlugRoute,
  EcosystemsIndexRoute: EcosystemsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
